name: Jekyll Site Website

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [event-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the latest branch
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0


      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing Bundle Packages
        run: python3 -m pip install elsa flask==2.0.1 flask_flatpages==0.7.3 frozen_flask==0.18 pygments==2.10.0 werkzeug==2.0.3

      - name: Installing Dependencies
        run: python3 setup.py freeze

      - name: Installing Dependencies
        run: ls -altr

      - name: Installing Dependencies
        run: mv _build docs

      - name: Get Excess Time
        id: excesstime
        uses: nanzm/get-time-action@v1.0
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release_${{ steps.excesstime.outputs.time }}
          release_name: Release_${{ steps.excesstime.outputs.time }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
